# SPDX-FileCopyrightText: 2024 Carlo Castoldi <carlo.castoldi@outlook.com>
#
# SPDX-License-Identifier: CC0-1.0

repos:
-   repo: https://github.com/fsfe/reuse-tool
    rev: v3.0.2
    hooks:
    - id: reuse
