# SPDX-FileCopyrightText: 2022 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: CC0-1.0

name: Make draft release

on:
  workflow_dispatch:

jobs:
  jpackage:
    name: Run JPackage
    uses: ./.github/workflows/jpackage.yml

  javadoc:
    name: Deploy JavaDoc
    uses: ./.github/workflows/publish_javadoc.yml

  release:
    needs: [jpackage, javadoc]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4

      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create --draft ${{ github.ref_name }} --title ${{ github.ref_name }} build/*.jar
